/* Paste pages. Each /<slug>/index.html is a thin shell generated by the dash
   (genPasteShell) with the title, description and content baked in, so the
   page is complete without JS. This script enhances it: links become
   clickable, copy / download / share / wrap actions appear, the UI follows
   PT|EN, and the content is refreshed from /pastes.json in case it was edited
   by hand after the shell was generated. On hand-built pages (no data-slug)
   it only wires the theme and language buttons. */
(function () {
    'use strict';
    var P = window.lfPrefs;
    var T = {
        pt: {
            skip: 'Pular para o conteúdo', prefs: 'Preferências', theme: 'Alternar tema', back: '← pastes',
            copy: 'copiar', copied: 'copiado!', copy_failed: 'não foi possível copiar', download: 'baixar .txt', download_key: 'baixar .asc',
            share: 'compartilhar', wrap: 'sem quebra de linha', unwrap: 'quebrar linhas', copy_key: 'copiar chave',
            not_found: 'Paste não encontrado.', canonical: 'Página canônica das chaves:'
        },
        en: {
            skip: 'Skip to content', prefs: 'Preferences', theme: 'Toggle theme', back: '← pastes',
            copy: 'copy', copied: 'copied!', copy_failed: 'could not copy', download: 'download .txt', download_key: 'download .asc',
            share: 'share', wrap: 'no line wrap', unwrap: 'wrap lines', copy_key: 'copy key',
            not_found: 'Paste not found.', canonical: 'Canonical key page:'
        }
    };
    P.wire(T);

    var body = document.body;
    var slug = body.getAttribute('data-slug');
    var pre = document.getElementById('paste-body');
    if (!slug || !pre) return;

    var type = ['pgp', 'links'].indexOf(body.getAttribute('data-type')) !== -1 ? body.getAttribute('data-type') : 'text';
    var raw = pre.textContent;
    var wrapped = true;

    function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#x27;'); }

    /* Works on the raw text (not the escaped HTML) so query strings with &
       survive, and trailing punctuation stays outside the link. */
    var LINK_RE = /(https?:\/\/[^\s<>"'`]+)|([\w.+-]+@[\w-]+(?:\.[\w-]+)+)/g;
    function linkify(text) {
        var out = '', last = 0, m;
        LINK_RE.lastIndex = 0;
        while ((m = LINK_RE.exec(text))) {
            var token = m[0], trail = '';
            if (m[1]) { var t = token.match(/[.,;:!?)\]}]+$/); if (t) { trail = t[0]; token = token.slice(0, -trail.length); } }
            out += esc(text.slice(last, m.index));
            if (m[1]) out += '<a href="' + esc(token) + '" target="_blank" rel="noopener noreferrer">' + esc(token) + '</a>';
            else out += '<a href="mailto:' + esc(token) + '">' + esc(token) + '</a>';
            out += esc(trail);
            last = m.index + m[0].length;
        }
        return out + esc(text.slice(last));
    }

    /* type "links": a notice + link buttons, for pages like the school video
       projects. Rule (the dash preview uses the same one):
         - blocks are separated by a blank line;
         - a block whose last line is a URL → a link row, the lines above it
           are its caption (a trailing ":" is dropped);
         - a title line followed only by "- item" lines → a members list;
         - the first other block → the notice; later ones → plain text. */
    function renderLinks(text) {
        var html = '', noticeDone = false;
        text.split(/\n[ \t]*\n/).forEach(function (block) {
            var lines = block.split('\n').map(function (l) { return l.trim(); }).filter(Boolean);
            if (!lines.length) return;
            var last = lines[lines.length - 1];
            if (/^https?:\/\/\S+$/.test(last)) {
                var cap = lines.slice(0, -1).join(' ').replace(/:\s*$/, '');
                html += '<div class="block">' + (cap ? '<p>' + linkify(cap) + '</p>' : '') +
                    '<a class="link-row" href="' + esc(last) + '" target="_blank" rel="noopener noreferrer"><span class="link-url">' +
                    esc(last.replace(/^https?:\/\//, '')) + '</span><span class="link-arr" aria-hidden="true">↗</span></a></div>';
            } else if (lines.length > 1 && lines.slice(1).every(function (l) { return /^[-•*]\s+/.test(l); })) {
                html += '<div class="members"><span class="members-title">' + esc(lines[0].replace(/:\s*$/, '')) + '</span>' +
                    lines.slice(1).map(function (l) { return '<span>' + esc(l.replace(/^[-•*]\s+/, '')) + '</span>'; }).join('') + '</div>';
            } else if (!noticeDone) {
                noticeDone = true;
                html += '<div class="notice">' + linkify(lines.join('\n')) + '</div>';
            } else {
                html += '<p class="links-text">' + linkify(lines.join('\n')) + '</p>';
            }
        });
        return html;
    }

    function copyText(text) {
        if (navigator.clipboard && window.isSecureContext) return navigator.clipboard.writeText(text);
        return new Promise(function (resolve, reject) {
            var ta = document.createElement('textarea');
            ta.value = text; ta.setAttribute('readonly', ''); ta.style.position = 'fixed'; ta.style.opacity = '0';
            document.body.appendChild(ta); ta.select();
            try { document.execCommand('copy') ? resolve() : reject(new Error('copy')); } catch (e) { reject(e); }
            document.body.removeChild(ta);
        });
    }

    function download(name, text) {
        var url = URL.createObjectURL(new Blob([text], { type: 'text/plain;charset=utf-8' }));
        var a = document.createElement('a');
        a.href = url; a.download = name;
        document.body.appendChild(a); a.click(); document.body.removeChild(a);
        setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
    }

    var live = document.createElement('p');
    live.className = 'sr-only';
    live.setAttribute('aria-live', 'polite');
    document.body.appendChild(live);

    function button(key, onClick) {
        var b = document.createElement('button');
        b.type = 'button';
        b.className = 'act-btn';
        b.setAttribute('data-i18n', key);
        b.textContent = P.t(key);
        b.addEventListener('click', function () { onClick(b); });
        return b;
    }
    function flash(b, key) {
        b.textContent = P.t(key);
        b.classList.toggle('ok', key === 'copied');
        live.textContent = P.t(key);
        setTimeout(function () { b.textContent = P.t(b.getAttribute('data-i18n')); b.classList.remove('ok'); }, 2000);
    }

    var actions = document.createElement('div');
    actions.className = 'paste-actions';
    actions.appendChild(button(type === 'pgp' ? 'copy_key' : 'copy', function (b) {
        copyText(raw).then(function () { flash(b, 'copied'); }, function () { flash(b, 'copy_failed'); });
    }));
    actions.appendChild(button(type === 'pgp' ? 'download_key' : 'download', function () {
        download(slug + (type === 'pgp' ? '.asc' : '.txt'), raw.replace(/\n?$/, '\n'));
    }));
    if (type === 'text') {
        actions.appendChild(button('wrap', function (b) {
            wrapped = !wrapped;
            pre.classList.toggle('nowrap', !wrapped);
            b.setAttribute('data-i18n', wrapped ? 'wrap' : 'unwrap');
            b.textContent = P.t(b.getAttribute('data-i18n'));
        }));
    }
    if (navigator.share) {
        actions.appendChild(button('share', function () {
            navigator.share({ title: document.title, url: location.href.split('#')[0] }).catch(function () { /* dismissed */ });
        }));
    }
    pre.parentNode.insertBefore(actions, type === 'pgp' ? pre : pre.parentNode.firstChild);

    if (type === 'pgp') {
        var note = document.createElement('p');
        note.className = 'note';
        note.innerHTML = '<span data-i18n="canonical">' + esc(P.t('canonical')) + '</span> <a href="https://keys.lucafchala.com/">keys.lucafchala.com</a>';
        actions.parentNode.insertBefore(note, actions);
    }

    var view = null;
    function render() {
        if (type === 'links') {
            /* The <pre> keeps the raw text (copy/download, no-JS fallback). */
            if (!view) { view = document.createElement('div'); view.className = 'links-view'; pre.parentNode.insertBefore(view, pre.nextSibling); pre.hidden = true; }
            view.innerHTML = renderLinks(raw);
            return;
        }
        pre.innerHTML = type === 'text' ? linkify(raw) : esc(raw);
    }
    render();

    fetch('/pastes.json', { cache: 'no-cache' })
        .then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); })
        .then(function (data) {
            var p = (data.pastes || []).filter(function (x) { return x.slug === slug; })[0];
            if (!p) { if (!raw.trim()) pre.outerHTML = '<p class="not-found" data-i18n="not_found">' + esc(P.t('not_found')) + '</p>'; return; }
            var rule = document.getElementById('paste-rule');
            if (rule && p.subtitle) rule.textContent = p.subtitle;
            if (typeof p.content === 'string' && p.content !== raw) { raw = p.content; render(); }
        })
        .catch(function () { /* the baked content is already on the page */ });

    if ('serviceWorker' in navigator) {
        window.addEventListener('load', function () { navigator.serviceWorker.register('/sw.js').catch(function () {}); });
    }
})();
